### ISSUE TITLE
How to use with image cropper?

### ISSUE THREAD

**Issue by kolkov** [j-zeng/angular2-http-file-upload#1]
Hi! Is it possible to use this service with image cropper or image preview?

**Comment by j-zeng** [comment]
You simply need a reference to the cropped image file. If you have that, you can set it as the file property on your UploadItem. If you are following the README example, then under 'Use the file upload service in a component' replace:

_let myUploadItem = new MyUploadItem((<HTMLInputElement>window.document.getElementById('myFileInputField')).files[0]);_

with:

_let croppedImageFile = getCroppedImageFileSomehow();   // presumably from an image cropping library of your choice
let myUploadItem = new MyUploadItem(croppedImageFile);_

(The rest of the example would be the same.)
