### ISSUE TITLE
Property 'onError' does not exist on type 'Uploader'

### ISSUE THREAD

**Issue by shabbir-dhangot** [j-zeng/angular2-http-file-upload#5]
Change Readme file. 
From 
 `this.uploaderService.onError = (item, response, status, headers) => {
             // error callback
        };`
To
`this.uploaderService.onErrorUpload = (item, response, status, headers) => {
             // error callback
        };`

**Comment by j-zeng** [comment]
Thank you for pointing this out. I've updated the README.
